### ISSUE TITLE
How to you use multiple save files for multiple characters?

### ISSUE THREAD

**Issue by Neurrone** [Wensber/TextTheSpire#10]
I've successfully completed an ironclad run. 

I started a silent run, my first time doing so and I used the "start silent" command.

Unfortunately, after restarting the game, it seems that continue is stuck / saved on my third act boss fight for the Ironclad run.

How can I have it continue my Silent run instead?

**Comment by Wensber** [comment]
Hello,

Go to the saves folder in the main Slay the Spire folder. These are the
current runs. The ironclad run wasn't properly deleted. This is a known
issue with the mod and I'm not quite sure how it happens. Delete the runs
you don't want and keep the ones you do. If you are not sure which is which
you can just move them somewhere else and check which is which.

Thanks,
Wensber

**Comment by Neurrone** [comment]
Thanks, that worked.

Suggest putting this in the readme or some other visible place because this is a pretty bad issue if you don't know what the workaround is.

**Comment by Neurrone** [comment]
Hm, this is fairly annoying. After deleting the files, they keep on coming back for some reason after a while, so need to be periodically re-deleted.

**Comment by Wensber** [comment]
Hello,

Honestly I have no idea how the run save system works in the game. Have you
used the restart function? One problem I can think of is that the mod
currently doesn't use the abandon run option and just starts a new run
which I imagine could cause this issue. However I don't think this would
cause deleted saves to come back.

Thanks,
Wensber

**Comment by Neurrone** [comment]
I'm using the `restart <classname> <ascension_level>` command.

**Comment by Wensber** [comment]
Hello,

That makes sense then. Normally the game doesn't let you start a run with
an existing run. You'd have to abandon or finish the run first. My mod
currently lets you start a run even if a run exists and that seems to cause
some issues inconsistently. I might need to replace restart with abandon.

Thanks,
Wensber

**Comment by Neurrone** [comment]
Oh, was I supposed to have used the start instead of the restart command instead? I remember trying that and it not working or something, which was why I used restart.

Its also odd though because for the save files that keep on being loaded, they are for completed runs where I either died or defeated the act 3 boss.

**Comment by Wensber** [comment]
Hello,

The restart command only appears if there is an existing run. You should
use the continue command to continue it. The start and restart command
specifically do not appear together as a precaution against people
accidentally overwriting runs. When a run completes the save is supposed to
disappear.

Thanks,
Wensber

**Comment by Neurrone** [comment]
Yeah, the bug here seems to be that completed runs don't seem to disappear for me. I'm not sure if I'm doing anything wrong. I think I enter "proceed" a couple of times to get past the score and unlocked relics/card screens, which puts me back to the main menu.

**Comment by Wensber** [comment]
Hello,

I doubt it has anything to do with the end of run screens. Try to avoid
using the restart command and see if that eventually clears up the issue.

Thanks,
Wensber

**Comment by Neurrone** [comment]
If I don't use the restart command and try to use start, start doesn't work for me.

**Comment by Wensber** [comment]
Hello,

What does the Choices window display? If it displays restart then you have
a saved run active and can either restart or continue. In this case start
will not work. If you want to get rid of a saved run either delete it from
the folder or continue the run and intentionally lose. When there is no
saved run the Choices window will display start and the start command will
work.

Thanks,
Wensber

**Comment by Neurrone** [comment]
Thanks, I've just manually deleted all the files in my saves folder again and I now see the start option in choices.

Will see if the saved games that I deleted come back or not like it did previously.

**Comment by Neurrone** [comment]
Yup, just confirmed that the completed runs's save files still keeps on reappearing and pressing continue would put you in the middle of the last boss's combat.

**Comment by Neurrone** [comment]
The abandon command seems to work for me, will close. Thanks for the fix!
