### ISSUE TITLE
Option to get potions should not appear if you have Sozu

### ISSUE THREAD

**Issue by Neurrone** [Wensber/TextTheSpire#11]
As it says on the title. I don't know if visually the options to get potions from monster drops or shops appears. If it doesn't, then it shouldn't show up on the mod either.

The options don't do anything when selected, so it is still working as intended.

**Comment by ogomez92** [comment]
Um, the reason why you can't get any more potions is because your potion slots are full. IF there is a potion reward is because there is one, you just can't get it.

**Comment by Wensber** [comment]
Hello,

This is working as intended. Sozu does not remove  the option to get
potions. It just prevents potions from entering a potion slot. You are
normally allowed to select potions, buy them in shops, pick them from
events, but they just don't enter a potion slots.

Thanks,
Wensber

**Comment by Neurrone** [comment]
Ah, didn't realize the option still appeared.

Closing as this is working as intended.
