### ISSUE TITLE
Request for enhancements to some information displays

### ISSUE THREAD

**Issue by Neurrone** [Wensber/TextTheSpire#12]
Hi,

1. It would be helpful if the help text (e.g, typing choice 2 when selecting a card) also stated the rarity of the card. I understand this does show up visually. Useful for beginners to the game especially.
2. When looking at the help text of a relic e.g typing relic 2, it would be extremely helpful if relics that had charges on them also displayed the number of charges in the help text as well. This makes it much more convenient to find out how many attacks I need before my next attack hits for double damage for example. Right now, this requires scanning through the relic window.

**Comment by ogomez92** [comment]
Yes please. To the first one especially.

**Comment by Wensber** [comment]
Hello,

Those seem like easy fixes. I'll see if I can include them in the next
update.

Thanks,
Wensber

**Comment by Neurrone** [comment]
Thanks @Wensber. This has now been implemented and is working great. Closing.
