### ISSUE TITLE
Punctuation for path command output

### ISSUE THREAD

**Issue by Neurrone** [Wensber/TextTheSpire#14]
Hi,

It would be much easier to digest if this output:

```
Elite 3 Rest 1 Shop 1 Unknown 1 Monster 2 
Elite 6 2 Monster 7 1 Rest 8 0 Treasure 9 0 Elite 10 0 Shop 11 1 Monster 12 1 Unknown 13 0 Elite 14 1 
```

Had commas inserted so that it looks like this:

```
Elite 3, Rest 1, Shop 1, Unknown 1, Monster 2 
Elite 6 2, Monster 7 1, Rest 8 0, Treasure 9 0, Elite 10 0, Shop 11 1, Monster 12 1, Unknown 13 0, Elite 14 1 
```

The extra commas causes a screen reader to pause slightly which makes this large chunk of text much much easier to digest.

**Comment by Wensber** [comment]
Hello,

I see. That makes sense. I'll add it in the next update.

Thanks,
Wensber

**Comment by Neurrone** [comment]
Thanks, this works great in V1.7. Closing.
