### ISSUE TITLE
Ability to see draw pile

### ISSUE THREAD

**Issue by sukiletxe** [Wensber/TextTheSpire#15]
There are some cards which interact with the draw pile (shuffling it, putting things at its top or the bottom, etc.). I know that Telnet The Spire can render this pile visible (I've tried it but I don't like how the map is rendered there). Could it be possible to add it here too?
Thanks for making this addictive game accessible, you have no idea how much we blind players enjoy it.

**Comment by ogomez92** [comment]
Hey Sukil.
The draw pile is visible by typing deck, during combats it will display
your draw pile.

Hope this helps.

**Comment by sukiletxe** [comment]
Oh, thanks! I was confused by the help message. Closing.
