### ISSUE TITLE
Bug: Trying to "map" or "path" to an unreachable destination crashes the game

### ISSUE THREAD

**Issue by pitermach** [Wensber/TextTheSpire#16]
Steps to reproduce:

- Start a game and climb a floor or two.
- Then, try to either use the map or path command specifying one of the previous floors that you passed, IE type in map 1 1 if you're on floor 2.

This should probably just do nothing or say that this destination is unreachable. Instead, it currently causes the entire game to crash. I came across this bug when I accidentally made a typo while trying to navigate somewhere.

**Comment by Wensber** [comment]
I will test this out and fix it for the next update. It definitely should
just do nothing.

**Comment by pitermach** [comment]
The latest version fixed this crash. Thanks!
