### ISSUE TITLE
Bug/Suggestion: Stop tracking a destination once you reach it

### ISSUE THREAD

**Issue by pitermach** [Wensber/TextTheSpire#17]
Currently, if you tell TextTheSpire to guide you to a specific room, the tracking never stops, so once you pass the room every path from then on will just say it diverges. I think it'd be a lot cleaner if, once you reach your destination, tracking would just turn off so you wouldn't have the unnecessary "diverge" text next to everything.

**Comment by Wensber** [comment]
I remember someone mentioning this before. I guess I forgot to do that.
Will include in next update.

**Comment by pitermach** [comment]
Added in latest version, thanks for the change.
