### ISSUE TITLE
Suggestion: Don't require a potion target if there's only one

### ISSUE THREAD

**Issue by pitermach** [Wensber/TextTheSpire#18]
The title pretty much says everything for this one. :) At the moment, if a potion requires a specific target, you always have to specify one, while for cards if there is only one monster left you can just type in the card number on its own and it'll be played so I think potions should also work like this for consistency. I keep trying to use potions the same way as cards and sometimes forget you need to always specify a target.

**Comment by Wensber** [comment]
That sounds like a good idea. Will include in next update.

**Comment by pitermach** [comment]
This is now working like this in the latest version, thanks for the change
