### ISSUE TITLE
Possibility to show both coordinates in run history?

### ISSUE THREAD

**Issue by sukiletxe** [Wensber/TextTheSpire#19]
Currently, run history, when instructed to show the path taken, only shows the floor number, and the type of cell. Would it be possible to show also the cell number (1-5)? This would help a lot in repeating runs.
Thanks for this awesome mod!

**Comment by Wensber** [comment]
Hello,
Sadly the game doesn't store that info so I won't be able to display it.
Thanks,
Wensber

**Comment by sukiletxe** [comment]
Oh, that's right then, I'm closing this. Thanks again!
