### ISSUE TITLE
game crash on death

### ISSUE THREAD

**Issue by Valmorian** [Wensber/TextTheSpire#21]
was told that the problem was tex tthe spire, so I am sending you my log
[crash info from mod the spire.txt](https://github.com/Wensber/TextTheSpire/files/5647524/crash.info.from.mod.the.spire.txt)

**Comment by Timtam** [comment]
Seems to be related to the new changes introduced in the 30/11 update of text the spire - modthespire (or at least the mod launcher) got an update as well. Death, as well as victory (beating stage 3 and viewing the unlocks) crashes the game right now.

**Comment by Timtam** [comment]
oh, and when abandoning a game. this might be the quickest way to reproduce the crash.

**Comment by Valmorian** [comment]
so just posting this here it also crashes when I pick up certain relics, but three is no log to show

**Comment by Wensber** [comment]
As far as I can tell, these issues are caused by Slay the Spire changing or
renaming some of the objects/classes. In theory shouldn't be that hard to
fix. The main problem is finding all of the crashes. Will most likely take
the approach of fixing them as they are reported.

**Comment by Valmorian** [comment]
no problem, thanks for all the work!
