### ISSUE TITLE
Help is not shown when querying help about windows

### ISSUE THREAD

**Issue by sukiletxe** [Wensber/TextTheSpire#24]
I cannot get help for window commands (deck, discard, etc.). Weirdly I took a look at the code and everything seems fine. The rest of the commands (tried with potion, path, ascension and lang) work fine. I tried debugging mts and failed spetacularly.

**Comment by Wensber** [comment]
Hello,

Found the issue. It was a problem with the json file I had the help text
in. The root of the problem was the fact that all commands are set to
lowercase. In the json file the keys for the windows had an uppercase
letter. I changed it to all lowercase so it should work fine now.

Wensber

**Comment by sukiletxe** [comment]
Will test when the new version is out. Weirdly, before creating the issue, I looked at that file, tried typing the commands the same way they were writen in the json and still didn't work.

**Comment by Wensber** [comment]
That makes sense. The file had the keys with a capital letter. For example
"Deck". You input "help Deck" but it gets set to lowercase before being
parsed as a command so it becomes "help deck". Thus it was never able to
match with the window commands as they all had a capital letter. I changed
the keys to be all lowercase.

**Comment by sukiletxe** [comment]
Oh I see, thanks!
