### ISSUE TITLE
confirm support for act 4

### ISSUE THREAD

**Issue by Timtam** [Wensber/TextTheSpire#27]
I'm currently trying to unlock act 4, but it doesn't seem to happen. Do you know if:

* TextTheSpire has support for displaying the "key icon", meaning the icon that is displayed as soon as the player can actually gather the keys during a run to beat act 4 of the game?
* TextTheSpire actually allows to collect the keys, meaning that they'll properly show up during e.g. visits of the resting side, boss battle rewards etc?
* beating actual act 4 is supported, especially the kinda special shield and sword boss battle (which seems to incooperate some weird fighting mechanics)?

Thanks.

**Comment by pitermach** [comment]
Yes it does, I managed to get to Act 4 and even beat it once or twice though it's not easy. To answer your questions, the keys will just appear where you'd expect - as an option in treasure chests, as "recall" in rest sights, while the special elite encounter will be marked as "emerald key" on the map so you can navigate to it easily.

**Comment by Timtam** [comment]
great, thanks for clarifying that. I was trying to figure out if my STS or TTS was at fault here. I already have all classes at at least ascension 2 or 3, but no act 4 unlocked yet, means I cannot even collect the keys and I don't know why. I do have the achievement enabler though, because that one seems to be needed to actually unlock the Watcher. Do you know if I have to have some dedicated mod installed to unlock act 4 or something? Because AFAIK all I have to do to unlock act 4 is to play through the game with all 3 main classes once.
