### ISSUE TITLE
NVDA does not speak when I write and press enter.

### ISSUE THREAD

**Issue by audiogamer22** [Wensber/TextTheSpire#31]
I load all the mods, download java and instal it, everything seams to run fine but when I write in the prompt window and pres enter; nothing is read out to me.

I can view the text in the other windows but pressing control? left and right doe s not seam to move me through the windows.

I have RTS installed too.

Is there a way I can show you some code or something so you can see what's going on?

**Comment by pitermach** [comment]
If you have RTS installed, make sure you run it either before or after running the game, then you should have speech, and the review keys are Alt+Arrows, not CTRL. If after you run both you still don't get any speech, please open an issue in https://github.com/pitermach/readthespire/ and I'll look into it tomorrow.
