### ISSUE TITLE
Unable to leave Niao conversation when first starting daily climb

### ISSUE THREAD

**Issue by pitermach** [Wensber/TextTheSpire#6]
Steps to reproduce:

- Start Slay the Spire
- Type daily to go into the daily climb and then embark to start the game
- Try talking to Niao

At this point, after you press 1 to talk and the option to leave comes up, it doesn't do anything. The only way to proceed from here is to quit out of the game, start it up again and type in continue to reload from save. Then you'll be back in the Niao conversation except this time you're actually able to leave it and play.

**Comment by Wensber** [comment]
Hello,

I've heard about this but haven't gotten a chance to check it out. Is it
consistent? When did this start happening? Could it possibly be because of
a specific mod?

I will try to replicate this and then see if I can fix it.

Thanks,
Wensber

**Comment by blindndangerous** [comment]
For me, it just started happening last night.  I'm not sure if this has to due with a mod though, but even if you use OCR to click talk, then leave, you can't do anything until you quit and restart the game.

**Comment by Wensber** [comment]
Hello,

I have figured out the issue and have fixed it. I plan to fix some other
issues and then release it later today.

Thanks,
Wensber

**Comment by pitermach** [comment]
Thanks, this now works beautifully in the new version!
